### ISSUE TITLE
Error during make process

### ISSUE THREAD

**Issue by wildra** [borisboc/RaspberryPi-ADC-DAC#1]
Hello, 

Iḿ trying to run your code on an rpi 3B+ with the latest raspian image.
Did follow your install instructions but the following error occurs during make process:

**/home/pi/RaspberryPi-ADC-DAC/AD-DA-WS-RPI/AD-DA-WS-RPI.c: In function ‘ADC_DAC_Init’:
/home/pi/RaspberryPi-ADC-DAC/AD-DA-WS-RPI/AD-DA-WS-RPI.c:520:17: error: void value not ignored as it ought to be
  int spiBegin = bcm2835_spi_begin();**

Youŕe right, the codes provided by waveshare are not satisfying at all
so i really would like to test yours.
Any suggestions what could be the rootcause?

Many thanks!

**Comment by AKEOPLUS-boris-bocquet** [comment]
Hi Wildra,

good to ear that you are keen to use this code.

Which version of BCM2835 are you using? On the version I tried (1.55) and in the current version (1.56) the signature of  bcm2835_spi_begin() is correct.
http://www.airspayce.com/mikem/bcm2835/group__spi.html

**Comment by wildra** [comment]
Hi,

thats a quick response! :)

I did use version 1.45.
Somehow, my board is not working with versions 1.55 & 1.56.
Installed V1.50 now and all of a sudden, it worked!

Many Thanks for your work and help!

**Comment by AKEOPLUS-boris-bocquet** [comment]
Good to know. Please star the project if you like it. And if you want, you can propose some improvements in the code (e.g. pull request or email / message as you want).
Boris

**Comment by AKEOPLUS-boris-bocquet** [comment]
I added a remark in the README.MD : 

Remarks : tested with version 1.55. It looks like it is not compiling with versions < 1.50 because bcm2835_spi_begin() changed its signature.

**Comment by AKEOPLUS-boris-bocquet** [comment]
Dear Wildra,
indeed my code was not working properly with bcm V1.56. Because Mike finnally implemented the bit order : previously, there were no code behind meaning that now it matters if you call this function. This is corrected on current revision 22e4ecd04896c7cc2c74ff92b4207101c18a4019 . Maybe you should give a try. 
Kind Regards.
Boris
